version: "3.8"

services:
  flask_app:
    build: .
    command: python /app/run.py
    restart: always
    ports:
      - "4200:4200"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - database_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - nginx_network
    depends_on:
      - flask_app

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - database_network

volumes:
  postgres_data:

networks:
  database_network:
    name: database_network
    driver: bridge
  nginx_network:
    name: nginx_network
    driver: bridge
